@startuml

title __THEME's Class Diagram__\n

  namespace com.aaron.justlike {
    namespace others.theme {
      interface com.aaron.justlike.others.theme.IThemeCommunicable {
          {abstract} + onTap()
      }
    }
  }
  

  namespace com.aaron.justlike {
    namespace others.theme {
      class com.aaron.justlike.others.theme.ThemeActivity {
          {static} - CURRENT_CHECK : String
          {static} - CURRENT_THEME : String
          {static} - PREFERENCES_THEME : String
          {static} - PREFERENCES_THEME_CHECK : String
          - mActionBar : ActionBar
          - mExecutorService : ExecutorService
          - mIconBack : Drawable
          - mLayoutManager : LinearLayoutManager
          - mToolbar : Toolbar
          + onBackPressed()
          + onOptionsItemSelected()
          + onTap()
          + onWindowFocusChanged()
          # onCreate()
          - initIconColor()
          - initRecyclerView()
          - initToolbar()
          - initView()
          - reboot()
          - saveTheme()
      }
    }
  }
  

  namespace com.aaron.justlike {
    namespace others.theme {
      class com.aaron.justlike.others.theme.ThemeAdapter {
          {static} ~ BLACK : int
          {static} ~ BLUE : int
          {static} ~ GREEN : int
          {static} ~ GREY : int
          {static} ~ JUST_LIKE : int
          {static} ~ ORANGE : int
          {static} ~ PINK : int
          {static} ~ PURPLE : int
          {static} ~ RED : int
          {static} ~ WHITE : int
          - mContext : Context
          - mCurrentCheck : int
          - mList : List<Integer>
          + getItemCount()
          + onBindViewHolder()
          + onCreateViewHolder()
          ~ ThemeAdapter()
          - initThemeColor()
          - initThemeName()
      }
    }
  }
  

  namespace com.aaron.justlike {
    namespace others.theme {
      class com.aaron.justlike.others.theme.ThemeAdapter.ViewHolder {
          ~ background : CircleImageView
          ~ check : ImageView
          ~ checkbox : ViewGroup
          ~ imageView : ImageView
          ~ itemView : View
          ~ themeName : TextView
          ~ ViewHolder()
      }
    }
  }
  

  com.aaron.justlike.others.theme.ThemeActivity .up.|> com.aaron.justlike.others.theme.IThemeCommunicable
  com.aaron.justlike.others.theme.ThemeActivity -up-|> com.aaron.justlike.common.CommonActivity
  com.aaron.justlike.others.theme.ThemeAdapter -up-|> androidx.recyclerview.widget.RecyclerView.Adapter
  com.aaron.justlike.others.theme.ThemeAdapter +-down- com.aaron.justlike.others.theme.ThemeAdapter.ViewHolder
  com.aaron.justlike.others.theme.ThemeAdapter.ViewHolder -up-|> androidx.recyclerview.widget.RecyclerView.ViewHolder


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
