@startuml

title __IMPL's Class Diagram__\n

  namespace com.aaron.base {
    namespace impl {
      abstract class com.aaron.base.impl.ObserverImpl {
          + onComplete()
          + onError()
          + onNext()
          + onSubscribe()
      }
    }
  }
  

  namespace com.aaron.base {
    namespace impl {
      abstract class com.aaron.base.impl.OnClickListenerImpl {
          {static} - TAG : String
          - mClickInterval : long
          - mLastClickTime : long
          + OnClickListenerImpl()
          + OnClickListenerImpl()
          + getClickInterval()
          + onClick()
          {abstract} + onViewClick()
          + setClickInterval()
      }
    }
  }
  

  namespace com.aaron.base {
    namespace impl {
      abstract class com.aaron.base.impl.OnPageChangeListenerImpl {
          + onPageScrollStateChanged()
          + onPageScrolled()
          + onPageSelected()
      }
    }
  }
  

  namespace com.aaron.base {
    namespace impl {
      class com.aaron.base.impl.SingleObserverImpl {
          + onError()
          + onSubscribe()
          + onSuccess()
      }
    }
  }
  

  namespace com.aaron.base {
    namespace impl {
      abstract class com.aaron.base.impl.TextWatcherImpl {
          + afterTextChanged()
          + beforeTextChanged()
          + onTextChanged()
      }
    }
  }
  

  com.aaron.base.impl.ObserverImpl .up.|> io.reactivex.Observer
  com.aaron.base.impl.OnClickListenerImpl .up.|> android.view.View.OnClickListener
  com.aaron.base.impl.OnPageChangeListenerImpl .up.|> androidx.viewpager.widget.ViewPager.OnPageChangeListener
  com.aaron.base.impl.SingleObserverImpl .up.|> io.reactivex.SingleObserver
  com.aaron.base.impl.TextWatcherImpl .up.|> android.text.TextWatcher


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
