@startuml

title __UTIL's Class Diagram__\n

  namespace com.aaron.justlike {
    namespace common {
      namespace util {
        class com.aaron.justlike.common.util.AlipayUtil {
            {static} - ALIPAY_PACKAGE_NAME : String
            {static} - INTENT_URL_FORMAT : String
            {static} + hasInstalledAlipayClient()
            {static} + startAlipayClient()
            {static} + startIntentUrl()
        }
      }
    }
  }
  

  namespace com.aaron.justlike {
    namespace common {
      namespace util {
        class com.aaron.justlike.common.util.AnimationUtil {
            {static} + handleBottomBar()
            {static} + handleImageEffect()
            {static} + hideBottomBar()
            {static} + hideBottomBar()
            {static} + hideProgressBar()
            {static} + hideToolbar()
            {static} + setBottomBar()
            {static} + setImageLarge()
            {static} + setImageSmall()
            {static} + showBottomBar()
            {static} + showBottomBar()
            {static} + showFakeView()
            {static} + showProgressBar()
            {static} + showProgressImage()
            {static} + showToolbar()
            {static} + showViewByAlpha()
        }
      }
    }
  }
  

  namespace com.aaron.justlike {
    namespace common {
      namespace util {
        class com.aaron.justlike.common.util.EmptyViewUtil {
            {static} + hideEmptyView()
            {static} + showEmptyView()
        }
      }
    }
  }
  

  namespace com.aaron.justlike {
    namespace common {
      namespace util {
        class com.aaron.justlike.common.util.FileUtil {
            {static} + deleteFile()
            {static} + getBitmapFormDrawable()
            {static} + getFileSize()
            {static} + getImageContentUri()
            {static} + getImageDate()
            {static} + getImageName()
            {static} + getImageSize()
            {static} + getImageSizeByMb()
            {static} + getImageWidthHeight()
            {static} + getLastModified()
            {static} + getLocalFiles()
            {static} + getPath()
            {static} + getUriFromPath()
            {static} + saveToCache()
            {static} + setWallpaper()
            {static} + sortByDate()
            {static} + sortByName()
            {static} + sortBySize()
        }
      }
    }
  }
  

  namespace com.aaron.justlike {
    namespace common {
      namespace util {
        class com.aaron.justlike.common.util.FileUtil.DownloadUtils {
            - downloadId : long
            - downloadManager : DownloadManager
            - mContext : Context
            - mFabType : int
            - mPhotoName : String
            - receiver : BroadcastReceiver
            + DownloadUtils()
            + downloadImage()
            - checkStatus()
        }
      }
    }
  }
  

  namespace com.aaron.justlike {
    namespace common {
      namespace util {
        class com.aaron.justlike.common.util.LogUtil {
            {static} + DEBUG : int
            {static} + ERROR : int
            {static} + INFO : int
            {static} + NOTHING : int
            {static} + TAG : String
            {static} + VERBOSE : int
            {static} + WARN : int
            {static} + level : int
            {static} + d()
            {static} + e()
            {static} + i()
            {static} + v()
            {static} + w()
        }
      }
    }
  }
  

  namespace com.aaron.justlike {
    namespace common {
      namespace util {
        class com.aaron.justlike.common.util.NotificationUtil {
            {static} - CHANNEL_ID : String
            {static} - CHANNEL_NAME : String
            {static} + createNotification()
            {static} + getNotification()
            {static} + getNotificationManager()
        }
      }
    }
  }
  

  namespace com.aaron.justlike {
    namespace common {
      namespace util {
        class com.aaron.justlike.common.util.SystemUtil {
            {static} + dp2px()
            {static} + getCreateDate()
            {static} + getCurrentDate()
            {static} + getLastModified()
            {static} + getRandomNum()
            {static} + getResolution()
            {static} + getUnsplashDate()
            {static} + getVersionName()
            {static} + isViewVisible()
            {static} + setIconEnable()
            {static} + showKeyboard()
        }
      }
    }
  }
  

  com.aaron.justlike.common.util.FileUtil +-down- com.aaron.justlike.common.util.FileUtil.DownloadUtils


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
