@startuml

title __TEST's Class Diagram__\n

  namespace com.aaron.base {
    namespace image {
      namespace test {
        class com.aaron.base.image.test.DefaultOption {
            # DefaultOption()
        }
      }
    }
  }
  

  namespace com.aaron.base {
    namespace image {
      namespace test {
        class com.aaron.base.image.test.DefaultOption.Builder {
            + Builder()
            + Builder()
            + Builder()
            + Builder()
            + Builder()
            + Builder()
            # actualBuilder()
            # createOptionInstance()
        }
      }
    }
  }
  

  namespace com.aaron.base {
    namespace image {
      namespace test {
        class com.aaron.base.image.test.GlideEngine {
            + init()
            + load()
            - request()
            - setListener()
        }
      }
    }
  }
  

  namespace com.aaron.base {
    namespace image {
      namespace test {
        interface com.aaron.base.image.test.ILoader {
            {abstract} + getImageEngine()
            {abstract} + load()
            {abstract} + setImageEngine()
        }
      }
    }
  }
  

  namespace com.aaron.base {
    namespace image {
      namespace test {
        interface com.aaron.base.image.test.ImageEngine {
            {abstract} + init()
            {abstract} + load()
        }
      }
    }
  }
  

  namespace com.aaron.base {
    namespace image {
      namespace test {
        class com.aaron.base.image.test.ImageLoader {
            {static} + get()
            + getImageEngine()
            + load()
            + setImageEngine()
            - ImageLoader()
        }
      }
    }
  }
  

  namespace com.aaron.base {
    namespace image {
      namespace test {
        class com.aaron.base.image.test.ImageLoader.Holder {
            {static} - INSTANCE : ImageLoader
        }
      }
    }
  }
  

  namespace com.aaron.base {
    namespace image {
      namespace test {
        abstract class com.aaron.base.image.test.ImageOption {
            # mAsBitmap : boolean
            # mAsDrawable : boolean
            # mAsFile : boolean
            # mAsGif : boolean
            # mBitmap : Bitmap
            # mCrossFadeDuration : int
            # mDrawable : Drawable
            # mDrawableId : int
            # mFile : File
            # mPlaceholderId : int
            # mString : String
            # mTarget : ImageView
            # mUri : Uri
            + getBitmap()
            + getCrossFadeDuration()
            + getDrawable()
            + getDrawableId()
            + getFile()
            + getListener()
            + getPlaceholderId()
            + getScaleType()
            + getString()
            + getTarget()
            + getUri()
            + isAsBitmap()
            + isAsDrawable()
            + isAsFile()
            + isAsGif()
            # ImageOption()
        }
      }
    }
  }
  

  namespace com.aaron.base {
    namespace image {
      namespace test {
        abstract class com.aaron.base.image.test.ImageOption.Builder {
            # asBitmap : boolean
            # asDrawable : boolean
            # asFile : boolean
            # asGif : boolean
            # bitmap : Bitmap
            # crossFadeDuration : int
            # drawable : Drawable
            # drawableId : int
            # file : File
            # placeholderId : int
            # string : String
            # target : ImageView
            # uri : Uri
            + Builder()
            + Builder()
            + Builder()
            + Builder()
            + Builder()
            + Builder()
            + addListener()
            + asBitmap()
            + asDrawable()
            + asFile()
            + asGif()
            + crossFade()
            + into()
            + placeholder()
            + scaleType()
            {abstract} # actualBuilder()
            {abstract} # createOptionInstance()
        }
      }
    }
  }
  

  namespace com.aaron.base {
    namespace image {
      namespace test {
        interface com.aaron.base.image.test.LoadListener {
            {abstract} + onFailure()
            {abstract} + onSuccess()
        }
      }
    }
  }
  

  namespace com.aaron.base {
    namespace image {
      namespace test {
        enum ScaleType {
          CENTER_CROP
          CENTER_INSIDE
          CIRCLE_CROP
          FIT_CENTER
        }
      }
    }
  }
  

  com.aaron.base.image.test.DefaultOption -up-|> com.aaron.base.image.test.ImageOption
  com.aaron.base.image.test.DefaultOption +-down- com.aaron.base.image.test.DefaultOption.Builder
  com.aaron.base.image.test.DefaultOption.Builder -up-|> com.aaron.base.image.test.ImageOption.Builder
  com.aaron.base.image.test.GlideEngine .up.|> com.aaron.base.image.test.ImageEngine
  com.aaron.base.image.test.ImageLoader .up.|> com.aaron.base.image.test.ILoader
  com.aaron.base.image.test.ImageLoader o-- com.aaron.base.image.test.ImageEngine : mImageEngine
  com.aaron.base.image.test.ImageLoader +-down- com.aaron.base.image.test.ImageLoader.Holder
  com.aaron.base.image.test.ImageOption o-- com.aaron.base.image.test.LoadListener : mListener
  com.aaron.base.image.test.ImageOption o-- com.aaron.base.image.test.ScaleType : mScaleType
  com.aaron.base.image.test.ImageOption +-down- com.aaron.base.image.test.ImageOption.Builder
  com.aaron.base.image.test.ImageOption.Builder o-- com.aaron.base.image.test.LoadListener : listener
  com.aaron.base.image.test.ImageOption.Builder o-- com.aaron.base.image.test.ScaleType : scaleType


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
