@startuml

title __UTIL's Class Diagram__\n

  namespace com.aaron.base {
    namespace util {
      class com.aaron.base.util.StatusBarUtils {
          {static} + setColor()
          {static} + setStatusBarLight()
          {static} + setTranslucent()
          {static} + setTranslucent()
          {static} + setTransparent()
          {static} + setTransparent()
          - StatusBarUtils()
          {static} - getStatusBarHeight()
      }
    }
  }
  

  namespace com.aaron.base {
    namespace util {
      class com.aaron.base.util.TimerUtils {
          {static} - TAG : String
          - mDisp : Disposable
          + TimerUtils()
          + cancel()
          + setListener()
          {static} + start()
          {static} + start()
          + start()
          + start()
      }
    }
  }
  

  namespace com.aaron.base {
    namespace util {
      class com.aaron.base.util.TimerUtils.CountDownUtil {
          - disp : Disposable
          + CountDownUtil()
          + cancel()
          + setListener()
          + start()
          + start()
          + start()
      }
    }
  }
  

  namespace com.aaron.base {
    namespace util {
      interface com.aaron.base.util.TimerUtils.Listener {
          {abstract} + onFinish()
          {abstract} + onProgress()
          {abstract} + onStart()
      }
    }
  }
  

  namespace com.aaron.base {
    namespace util {
      interface com.aaron.base.util.TimerUtils.OnFinishListener {
          {abstract} + onFinish()
      }
    }
  }
  

  namespace com.aaron.base {
    namespace util {
      class com.aaron.base.util.TimerUtils.SimpleListener {
          + onFinish()
          + onProgress()
          + onStart()
      }
    }
  }
  

  com.aaron.base.util.TimerUtils o-- com.aaron.base.util.TimerUtils.Listener : mListener
  com.aaron.base.util.TimerUtils +-down- com.aaron.base.util.TimerUtils.CountDownUtil
  com.aaron.base.util.TimerUtils +-down- com.aaron.base.util.TimerUtils.Listener
  com.aaron.base.util.TimerUtils +-down- com.aaron.base.util.TimerUtils.OnFinishListener
  com.aaron.base.util.TimerUtils +-down- com.aaron.base.util.TimerUtils.SimpleListener
  com.aaron.base.util.TimerUtils.CountDownUtil o-- com.aaron.base.util.TimerUtils.Listener : listener
  com.aaron.base.util.TimerUtils.SimpleListener .up.|> com.aaron.base.util.TimerUtils.Listener


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
