@startuml

title __UNSPLASH's Class Diagram__\n

  namespace com.aaron.justlike {
    namespace common {
      namespace http.unsplash {
        class com.aaron.justlike.common.http.unsplash.HeaderInterceptor {
            - clientId : String
            + HeaderInterceptor()
            + intercept()
        }
      }
    }
  }
  

  namespace com.aaron.justlike {
    namespace common {
      namespace http.unsplash {
        enum Order {
          LATEST
          OLDEST
          POPULAR
          order
        }
      }
    }
  }
  

  namespace com.aaron.justlike {
    namespace common {
      namespace http.unsplash {
        class com.aaron.justlike.common.http.unsplash.Unsplash {
            {static} - BASE_URL : String
            {static} - CLIENT_ID : String
            {static} - NEW_CLIENT_ID : String
            + getCuratedPhotos()
            {static} + getInstance()
            + getPhoto()
            + getPhotos()
            + getRandomPhotos()
            + searchCollections()
            + searchPhotos()
            + searchPhotosFromCollection()
            - Unsplash()
        }
      }
    }
  }
  

  namespace com.aaron.justlike {
    namespace common {
      namespace http.unsplash {
        class com.aaron.justlike.common.http.unsplash.Unsplash.Holder {
            {static} - INSTANCE : Unsplash
        }
      }
    }
  }
  

  com.aaron.justlike.common.http.unsplash.HeaderInterceptor .up.|> okhttp3.Interceptor
  com.aaron.justlike.common.http.unsplash.Unsplash o-- com.aaron.justlike.common.http.unsplash.interfaces.UnsplashService : mUnsplashService
  com.aaron.justlike.common.http.unsplash.Unsplash +-down- com.aaron.justlike.common.http.unsplash.Unsplash.Holder


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
