@startuml

title __REQUEST's Class Diagram__\n

  namespace com.aaron.justlike {
    namespace common {
      namespace http.glide {
        namespace request {
          class com.aaron.justlike.common.http.glide.request.BitmapRequest {
              - mRequestBuilder : RequestBuilder<Bitmap>
              + BitmapRequest()
              + centerCrop()
              + into()
              + listener()
              + load()
              + load()
              + load()
              + load()
              + override()
              + placeHolder()
              + placeHolder()
              + thumbnail()
              + thumbnail()
              + transition()
          }
        }
      }
    }
  }
  

  namespace com.aaron.justlike {
    namespace common {
      namespace http.glide {
        namespace request {
          class com.aaron.justlike.common.http.glide.request.DrawableRequest {
              - mRequestBuilder : RequestBuilder<Drawable>
              + DrawableRequest()
              + centerCrop()
              + into()
              + listener()
              + load()
              + load()
              + load()
              + load()
              + override()
              + placeHolder()
              + placeHolder()
              + thumbnail()
              + thumbnail()
              + transition()
          }
        }
      }
    }
  }
  

  namespace com.aaron.justlike {
    namespace common {
      namespace http.glide {
        namespace request {
          class com.aaron.justlike.common.http.glide.request.FileRequest {
              - mRequestBuilder : RequestBuilder<File>
              + FileRequest()
              + centerCrop()
              + into()
              + listener()
              + load()
              + load()
              + load()
              + load()
              + override()
              + placeHolder()
              + placeHolder()
              + thumbnail()
              + thumbnail()
              + transition()
          }
        }
      }
    }
  }
  

  namespace com.aaron.justlike {
    namespace common {
      namespace http.glide {
        namespace request {
          class com.aaron.justlike.common.http.glide.request.GifDrawableRequest {
              - mRequestBuilder : RequestBuilder<GifDrawable>
              + GifDrawableRequest()
              + centerCrop()
              + into()
              + listener()
              + load()
              + load()
              + load()
              + load()
              + override()
              + placeHolder()
              + placeHolder()
              + thumbnail()
              + thumbnail()
              + transition()
          }
        }
      }
    }
  }
  

  namespace com.aaron.justlike {
    namespace common {
      namespace http.glide {
        namespace request {
          interface com.aaron.justlike.common.http.glide.request.Request {
              {abstract} + centerCrop()
              {abstract} + into()
              {abstract} + listener()
              {abstract} + load()
              {abstract} + load()
              {abstract} + load()
              {abstract} + load()
              {abstract} + override()
              {abstract} + placeHolder()
              {abstract} + placeHolder()
              {abstract} + thumbnail()
              {abstract} + thumbnail()
              {abstract} + transition()
          }
        }
      }
    }
  }
  

  namespace com.aaron.justlike {
    namespace common {
      namespace http.glide {
        namespace request {
          interface com.aaron.justlike.common.http.glide.request.Request.Listener {
              {abstract} + onLoadFailed()
              {abstract} + onResourceReady()
          }
        }
      }
    }
  }
  

  com.aaron.justlike.common.http.glide.request.BitmapRequest .up.|> com.aaron.justlike.common.http.glide.request.Request
  com.aaron.justlike.common.http.glide.request.DrawableRequest .up.|> com.aaron.justlike.common.http.glide.request.Request
  com.aaron.justlike.common.http.glide.request.FileRequest .up.|> com.aaron.justlike.common.http.glide.request.Request
  com.aaron.justlike.common.http.glide.request.GifDrawableRequest .up.|> com.aaron.justlike.common.http.glide.request.Request
  com.aaron.justlike.common.http.glide.request.Request +-down- com.aaron.justlike.common.http.glide.request.Request.Listener


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
