@startuml

title __MANAGER's Class Diagram__\n

  namespace com.aaron.justlike {
    namespace common {
      namespace manager {
        class com.aaron.justlike.common.manager.ThemeManager {
            {static} - CURRENT_THEME : String
            {static} - PREFERENCES_NAME : String
            + getCurrentTheme()
            {static} + getInstance()
            + setTheme()
            - ThemeManager()
        }
      }
    }
  }
  

  namespace com.aaron.justlike {
    namespace common {
      namespace manager {
        class com.aaron.justlike.common.manager.ThemeManager.Holder {
            {static} - INSTANCE : ThemeManager
        }
      }
    }
  }
  

  namespace com.aaron.justlike {
    namespace common {
      namespace manager {
        enum Theme {
          BLACK
          BLUE
          GREEN
          GREY
          JUST_LIKE
          ORANGE
          PINK
          PURPLE
          RED
          WHITE
        }
      }
    }
  }
  

  namespace com.aaron.justlike {
    namespace common {
      namespace manager {
        class com.aaron.justlike.common.manager.UiManager {
            {static} + showLong()
            {static} + showLong()
            {static} + showShort()
            {static} + showShort()
            - UiManager()
        }
      }
    }
  }
  

  com.aaron.justlike.common.manager.ThemeManager o-- com.aaron.justlike.common.manager.ThemeManager.Theme : mCurrentTheme
  com.aaron.justlike.common.manager.ThemeManager +-down- com.aaron.justlike.common.manager.ThemeManager.Holder
  com.aaron.justlike.common.manager.ThemeManager +-down- com.aaron.justlike.common.manager.ThemeManager.Theme


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
