@startuml

title __ADAPTER's Class Diagram__\n

  namespace com.aaron.justlike {
    namespace common {
      namespace adapter {
        abstract class com.aaron.justlike.common.adapter.PhotoAdapter {
            # mAnimatedFlag : SparseBooleanArray
            # mContext : Context
            # mPhotoList : List<Photo>
            {static} - TYPE_FOOTER : int
            {static} - TYPE_NORMAL : int
            + PhotoAdapter()
            + clearAnimatedFlag()
            + getItemCount()
            + getItemViewType()
            + isFooterView()
            + onBindViewHolder()
            + onCreateViewHolder()
            {abstract} # bindHolder()
            {abstract} # createHolder()
        }
      }
    }
  }
  

  namespace com.aaron.justlike {
    namespace common {
      namespace adapter {
        class com.aaron.justlike.common.adapter.PhotoAdapter.FooterViewHolder {
            + FooterViewHolder()
        }
      }
    }
  }
  

  namespace com.aaron.justlike {
    namespace common {
      namespace adapter {
        class com.aaron.justlike.common.adapter.PhotoAdapter.ViewHolder {
            + authorImage : ImageView
            + authorName : TextView
            + imageView : ImageView
            + itemView : View
            + placeHolder : ImageView
            + ViewHolder()
        }
      }
    }
  }
  

  namespace com.aaron.justlike {
    namespace common {
      namespace adapter {
        abstract class com.aaron.justlike.common.adapter.SquareAdapter {
            # mContext : Context
            # mList : List<Image>
            + SquareAdapter()
            + getItemCount()
            + onBindViewHolder()
            + onCreateViewHolder()
            {abstract} # bindHolder()
            {abstract} # createHolder()
        }
      }
    }
  }
  

  namespace com.aaron.justlike {
    namespace common {
      namespace adapter {
        class com.aaron.justlike.common.adapter.SquareAdapter.ViewHolder {
            + ViewHolder()
        }
      }
    }
  }
  

  com.aaron.justlike.common.adapter.PhotoAdapter -up-|> androidx.recyclerview.widget.RecyclerView.Adapter
  com.aaron.justlike.common.adapter.PhotoAdapter +-down- com.aaron.justlike.common.adapter.PhotoAdapter.FooterViewHolder
  com.aaron.justlike.common.adapter.PhotoAdapter +-down- com.aaron.justlike.common.adapter.PhotoAdapter.ViewHolder
  com.aaron.justlike.common.adapter.PhotoAdapter.FooterViewHolder -up-|> androidx.recyclerview.widget.RecyclerView.ViewHolder
  com.aaron.justlike.common.adapter.PhotoAdapter.ViewHolder -up-|> androidx.recyclerview.widget.RecyclerView.ViewHolder
  com.aaron.justlike.common.adapter.SquareAdapter -up-|> androidx.recyclerview.widget.RecyclerView.Adapter
  com.aaron.justlike.common.adapter.SquareAdapter +-down- com.aaron.justlike.common.adapter.SquareAdapter.ViewHolder
  com.aaron.justlike.common.adapter.SquareAdapter.ViewHolder -up-|> androidx.recyclerview.widget.RecyclerView.ViewHolder
  com.aaron.justlike.common.adapter.SquareAdapter.ViewHolder o-- com.aaron.justlike.common.widget.SquareView : squareView


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
